### PR TITLE
Add Vpc Peering and Revise VPC to use golangsdk

### PR DESCRIPTION
**Pull request by Savasw**
This PR adds capability to manage OTC's  VPC Peering Connection resources and revises VPC to use golangsdk instead of gophercloud. The acceptance tests for all peering and vpc resources and datasources are passing.

### CODE REVIEW

**Comment by niuzhenguo** [comment]
@freesky-edward do we still accept PRs here? or all new PRs should go to terraform-providers/terraform-provider-opentelekomcloud.

**Comment by freesky-edward** [comment]
@niuzhenguo any impact if merge here fist?

**Comment by niuzhenguo** [comment]
@freesky-edward no, just wondering. seems we have changed to push new PRs to official repo for more than a month. I'm afraid the code base there is not same with this now.

**Comment by Savasw** [comment]
@niuzhenguo @freesky-edward shall i close this PR in favour of a new PR that has route and subnet too https://github.com/huaweicloud/terraform-provider-opentelekomcloud/pull/4

**Comment by niuzhenguo** [comment]
@Savasw sure.

**Pull request closed without merging**
